
create PROCEDURE SP_ALTA_ITEMPRESUPUESTO
@IDITEMPRESUPUESTO INT OUTPUT,
@IDPRESUPUESTO INT,
@CODPRODUCTO CHAR(6),
@CANTPRODUTO INT,
@MONTOITEM   INT,
@NROITEM INT
AS
insert into CT_ITEMPRESUPUESTO(IDPRESUPUESTO,CODPRODUCTO,CANTPRODUTO,MONTOITEM,NROITEM) 
values(@IDPRESUPUESTO,@CODPRODUCTO,@CANTPRODUTO,@MONTOITEM,@NROITEM);

SELECT @IDITEMPRESUPUESTO=MAX(IDITEMPRESUPUESTO) FROM CT_ITEMPRESUPUESTO






CREATE PROCEDURE SP_ALTA_PRESUPEUSTO
@IDPRESUPUESTO  INT OUTPUT,
@FECHAEMISIONPRESUPUESTO DATE,
@IDCLIENTE   INT,
@IDTECNICO  INT,
@TIEMPOMANOOBRA INT ,
@MONTOMANOOBRA INT
AS
insert into ct_presupuesto(FECHAEMISIONPRESUPUESTO,IDCLIENTE,IDTECNICO,TIEMPOMANOOBRA,MONTOMANOOBRA) 
values(@FECHAEMISIONPRESUPUESTO,@IDCLIENTE,@IDTECNICO,@TIEMPOMANOOBRA,@MONTOMANOOBRA);

SELECT @IDPRESUPUESTO=MAX(IDPRESUPUESTO) FROM CT_PRESUPUESTO
