CREATE PROCEDURE SP_ALTA_VISITA

@IDVISITA INT OUTPUT,    
@IDAGENDA INT,   
@IDFACTURA INT,   
@IDPRESUPPUESTO INT, 
@IDCLIENTE  INT, 
@IDDOMICILIO INT,
@INICIOPROGRAMADO DATETIME,        
@FINPROGRAMADO    DATETIME,       
@INICIOREAL DATETIME,              
@FINREAL DATETIME,                 
@MOTIVO NVARCHAR(500)

AS

INSERT INTO CT_VISITA(IDAGENDA,IDFACTURA,IDPRESUPPUESTO,IDCLIENTE,IDDOMICILIO,INICIOPROGRAMADO,FINPROGRAMADO,INICIOREAL,FINREAL,MOTIVO,ESTADO) 
VALUES (
@IDAGENDA,   
@IDFACTURA,   
@IDPRESUPPUESTO, 
@IDCLIENTE, 
@IDDOMICILIO,
@INICIOPROGRAMADO,        
@FINPROGRAMADO,       
@INICIOREAL,              
@FINREAL,                 
@MOTIVO,
'A');

SELECT @IDAGENDA = MAX(IDVISITA) FROM CT_VISITA;




