CREATE PROCEDURE SP_UPDATE_VISITA

@IDVISITA INT,    
@IDAGENDA INT,   
@IDFACTURA INT,   
@IDPRESUPPUESTO INT, 
@IDCLIENTE  INT, 
@IDDOMICILIO INT,
@INICIOPROGRAMADO DATETIME,        
@FINPROGRAMADO    DATETIME,       
@INICIOREAL DATETIME,              
@FINREAL DATETIME,                 
@MOTIVO NVARCHAR(500)

AS

UPDATE CT_VISITA
SET
IDAGENDA= @IDAGENDA,   
IDFACTURA=@IDFACTURA,   
IDPRESUPPUESTO=@IDPRESUPPUESTO, 
IDCLIENTE=@IDCLIENTE, 
IDDOMICILIO=@IDDOMICILIO,
INICIOPROGRAMADO=@INICIOPROGRAMADO,        
FINPROGRAMADO=@FINPROGRAMADO,       
INICIOREAL=@INICIOREAL,              
FINREAL=@FINREAL,                 
MOTIVO=@MOTIVO,
ESTADO ='M'
WHERE 
 IDVISITA = @IDVISITA
