SET DEFINE OFF;
Insert into TG_TIPODOCUMENTO
   (CODTIPODOCUMENTO, DESCTIPODOCUMENTO, ESTADO)
 Values
   ('CI', 'Cedula de Identidad','A');
Insert into TG_TIPODOCUMENTO
   (CODTIPODOCUMENTO, DESCTIPODOCUMENTO, ESTADO)
 Values
   ('CL', 'CUIL','A');
Insert into TG_TIPODOCUMENTO
   (CODTIPODOCUMENTO, DESCTIPODOCUMENTO, ESTADO)
 Values
   ('CT', 'CUIT','A');
Insert into TG_TIPODOCUMENTO
   (CODTIPODOCUMENTO, DESCTIPODOCUMENTO, ESTADO)
 Values
   ('DN', 'Documento Nacional de Identidad','A');
Insert into TG_TIPODOCUMENTO
   (CODTIPODOCUMENTO, DESCTIPODOCUMENTO, ESTADO)
 Values
   ('LC', 'Libreta Cívica','A');
Insert into TG_TIPODOCUMENTO
   (CODTIPODOCUMENTO, DESCTIPODOCUMENTO, ESTADO)
 Values
   ('LE', 'Libreta de Enrolamiento','A');
Insert into TG_TIPODOCUMENTO
   (CODTIPODOCUMENTO, DESCTIPODOCUMENTO, ESTADO)
 Values
   ('ND', 'No Definido','A');
Insert into TG_TIPODOCUMENTO
   (CODTIPODOCUMENTO, DESCTIPODOCUMENTO, ESTADO)
 Values
   ('NI', 'No Informado','A');
Insert into TG_TIPODOCUMENTO
   (CODTIPODOCUMENTO, DESCTIPODOCUMENTO, ESTADO)
 Values
   ('PP', 'Pasaporte','A');
Insert into TG_TIPODOCUMENTO
   (CODTIPODOCUMENTO, DESCTIPODOCUMENTO, ESTADO)
 Values
   ('RC', 'RUC','A');
Insert into TG_TIPODOCUMENTO
   (CODTIPODOCUMENTO, DESCTIPODOCUMENTO, ESTADO)
 Values
   ('RU', 'RUT','A');
COMMIT;
