--DROP DATABASE TNG24 
CREATE DATABASE TNG24 

USE TNG24

CREATE TABLE TG_DOMICILIO
(
IDDOMICILIO INT IDENTITY NOT NULL,
CALLE NVARCHAR NOT NULL,
NUMERO INT NOT NULL,
PISO INT,
DPTO CHAR(2),
TELEFONO NVARCHAR(50),
CODPROVINCIA CHAR(2) NOT NULL,
CODCIUDAD CHAR(5) NOT NULL,
CODIGOPOSTAL NVARCHAR(10) NOT NULL,
DESCLOCALIDAD NVARCHAR(40),
ESTADO CHAR(1) NOT NULL
CONSTRAINT CHK_ESTADO_DOMICILIO CHECK (ESTADO = 'A' OR ESTADO = 'M' OR ESTADO = 'B'),
CONSTRAINT  PK_DOMICILIO PRIMARY KEY (IDDOMICILIO)
--OK FOREING VER ABAJO
)




CREATE TABLE TG_PROVINCIA 
(
IDPROVINCIA INT IDENTITY NOT NULL,
CODPROVINCIA CHAR(2) NOT NULL,
DESCPROVINCIA NVARCHAR(40) NOT NULL,
ESTADO CHAR(1) NOT NULL
CONSTRAINT CHK_ESTADO_PROVINCIA CHECK (ESTADO = 'A' OR ESTADO = 'M' OR ESTADO = 'B')
CONSTRAINT   PK_PROVINCIA PRIMARY KEY  (IDPROVINCIA),
CONSTRAINT  UK_CODPROVINCIA UNIQUE(CODPROVINCIA)
--OK NO TIENE FOREING
)




CREATE TABLE TG_CIUDAD
(
IDCIUDAD INT IDENTITY NOT NULL,
CODCIUDAD CHAR(5) NOT NULL,
DESCCIUDAD NVARCHAR(100) NOT NULL,
CODPROVINCIA CHAR(2) NOT NULL,
ESTADO CHAR(1) NOT NULL
CONSTRAINT CHK_ESTADO_CIUDAD CHECK (ESTADO = 'A' OR ESTADO = 'M' OR ESTADO = 'B')
CONSTRAINT  PK_CIUDAD PRIMARY KEY (IDCIUDAD),
CONSTRAINT  UK_CODCIUDAD UNIQUE(CODCIUDAD)
--OK VER FOREING ABAJO
)






CREATE TABLE TG_CODIGOPOSTAL
(
IDCODIGOPOSTAL INT IDENTITY NOT NULL,
CODIGOPOSTAL NVARCHAR(10) NOT NULL,
CODPROVINCIA CHAR(2) NOT NULL,
DESCCODIGOPOSTAL NVARCHAR(40) NOT NULL,
CODCIUDAD CHAR(5) NOT NULL,
ESTADO CHAR(1) NOT NULL
CONSTRAINT CHK_ESTADO_CODIGOPOSTAL CHECK (ESTADO = 'A' OR ESTADO = 'M' OR ESTADO = 'B'),
CONSTRAINT  PK_CODIGOPOSTAL PRIMARY KEY (IDCODIGOPOSTAL),
CONSTRAINT  UK_CODIGOPOSTAL UNIQUE(CODIGOPOSTAL)
--OK VER ABAJO FOREING
)




CREATE TABLE TG_USUARIO
(
IDUSUARIO INT  NOT NULL,
USERNAME CHAR(6) NOT NULL,
PASS  CHAR(20)  NOT NULL, 
ESTADO CHAR(1) NOT NULL
CONSTRAINT CHK_ESTADO_USUARIO CHECK (ESTADO = 'A' OR ESTADO = 'M' OR ESTADO = 'B')
CONSTRAINT  PK_USUARIO PRIMARY KEY (IDUSUARIO),
CONSTRAINT  UK_USUARIO UNIQUE(USERNAME)
--OK VER ABAJO FOREING
)





CREATE TABLE TG_ENTE
(
IDENTE INT IDENTITY NOT NULL,
NOMBRE NVARCHAR(100),
APELLIDO NVARCHAR(100) NOT NULL,
CODTIPODOCUMENTO CHAR(3) NOT NULL,
NRODOCUMENTO VARCHAR(15) NOT NULL,
ESTADO CHAR(1) NOT NULL
CONSTRAINT  PK_ENTE PRIMARY KEY (IDENTE),
CONSTRAINT CHK_ESTADO_ENTE CHECK (ESTADO = 'A' OR ESTADO = 'M' OR ESTADO = 'B')
--OK VER FOREING ABAJO
)



CREATE TABLE TG_TIPODOCUMENTO
(
CODTIPODOCUMENTO CHAR(3) NOT NULL,
DESCTIPODOCUMENTO NVARCHAR(10) NOT NULL,
ESTADO CHAR(1) NOT NULL
CONSTRAINT CHK_ESTADO_TIPODOCUMENTO CHECK (ESTADO = 'A' OR ESTADO = 'M' OR ESTADO = 'B'),
CONSTRAINT  PK_TIPODOCUMENTO PRIMARY KEY (CODTIPODOCUMENTO),
CONSTRAINT  UK_TIPODOCUMENTO UNIQUE(DESCTIPODOCUMENTO)
--OK NO TIENE FOREING
)



CREATE TABLE TG_ROLLEMPPLEADO
(
CODROLLEMPPLEADO CHAR(3) NOT NULL,
DESCROLLEMPPLEADO NVARCHAR(40) NOT NULL,
ESTADO CHAR(1) NOT NULL
CONSTRAINT CHK_ESTADO_ROLLEMPPLEADO CHECK (ESTADO = 'A' OR ESTADO = 'M' OR ESTADO = 'B'),
CONSTRAINT  PK_ROLLEMPPLEADO PRIMARY KEY (CODROLLEMPPLEADO),
CONSTRAINT  UK_ROLLEMPPLEADO UNIQUE(DESCROLLEMPPLEADO)
--OK NO TIENE FOREING
)


CREATE TABLE CT_CLIENTE
(
IDCLIENTE INT NOT NULL,
TELEFONO NVARCHAR(50),
MAIL NVARCHAR(50),
IDDOMICILIO INT NOT NULL,
ESTADO CHAR(1) NOT NULL
CONSTRAINT CHK_ESTADO_CLIENTE CHECK (ESTADO = 'A' OR ESTADO = 'M' OR ESTADO = 'B'),
CONSTRAINT  PK_CLIENTE PRIMARY KEY (IDCLIENTE)
--OK VER FOREING ABAJO

)


CREATE TABLE CT_EMPLEADO
(
IDEMPLEADO INT  NOT NULL,
TELEFONO NVARCHAR(50),
MAIL NVARCHAR(50),
CODROLLEMPPLEADO CHAR(3) NOT NULL,
ESTADO CHAR(1) NOT NULL
CONSTRAINT CHK_ESTADO_EMPLEADO CHECK (ESTADO = 'A' OR ESTADO = 'M' OR ESTADO = 'B'),
CONSTRAINT  PK_EMPLEADO PRIMARY KEY (IDEMPLEADO)
--OK VER FOREGIN ABAJO 

)





CREATE TABLE ST_PRODUCTO
(
IDPRODUCTO INT IDENTITY NOT NULL,
CODPRODUCTO CHAR(6) NOT NULL,
DESCPRODUCTO NVARCHAR(200) NOT NULL,
STOCK INT NOT NULL, 
PTOPEDIDO INT NOT NULL,
PRECIO FLOAT NOT NULL,
ESTADO CHAR(1) NOT NULL
CONSTRAINT PK_PRODUCTO PRIMARY KEY (IDPRODUCTO),
CONSTRAINT  UK_CODPRODUCTO UNIQUE(CODPRODUCTO),
CONSTRAINT CHK_ESTADO_PRODUCTO CHECK (ESTADO = 'A' OR ESTADO = 'M' OR ESTADO = 'B'),
CONSTRAINT CHK_ESTADO_STOCK CHECK (STOCK>0),
CONSTRAINT CHK_ESTADO_PTOPEDIDO CHECK (PTOPEDIDO>=0),
CONSTRAINT CHK_ESTADO_PRECIO CHECK (PRECIO>=0)
--OK NO TIENE FOREING
)




CREATE TABLE ST_RETIROPRODUCTO
(
IDRETIROPRODUCTO INT IDENTITY NOT NULL,
NROLOTERETIRO INT NOT NULL,
FECHARETIRO DATE,
IDPRODUCTO INT,
CANT INT,
IDTECNICORETIRANTE INT,
ESTADORETIRO CHAR(3),
ESTADO CHAR(1) NOT NULL
CONSTRAINT  PK_RETIROPRODUCTO PRIMARY KEY(IDRETIROPRODUCTO),
CONSTRAINT CHK_ESTADO_RETIROPRODUCTO CHECK (ESTADO = 'A' OR ESTADO = 'M' OR ESTADO = 'B'),
CONSTRAINT CHK_ESTADO_ESTADORETIRO  CHECK (ESTADORETIRO = 'RET' OR ESTADORETIRO = 'PEN'),
CONSTRAINT CHK_CANT_RETIROPRODUCTO CHECK (CANT>0)
--OK VER ABAJO FOREING
)








CREATE TABLE ST_DEVOLUCIONPRODUCTO
(
IDDEVOLUCIONPRODUCTO INT IDENTITY NOT NULL,
NROLOTEDEVOLUCION INT NOT NULL,
FECHADEVOLUCION DATE,
IDPRODUCTO INT,
CANT INT,
IDTECNICODEVOLUCION INT,
IDENCRAGADOSTOCKDEVOLUCION INT, 
ESTADODEVOLUCION CHAR(3),
ESTADO CHAR(1) NOT NULL
CONSTRAINT PK_DEVOLUCIONPRODUCTO  PRIMARY KEY (IDDEVOLUCIONPRODUCTO),
CONSTRAINT CHK_ESTADO_DEVOLUCIONPRODUCTO CHECK (ESTADO = 'A' OR ESTADO = 'M' OR ESTADO = 'B'),
CONSTRAINT CHK_ESTADO_ESTADODEVOLUCION  CHECK (ESTADODEVOLUCION = 'DEV' OR ESTADODEVOLUCION = 'PEN'),
CONSTRAINT CHK_CANT_DEVOLUCIONPRODUCTO CHECK (CANT>0)
--OK VER ABAJO FOREING
)


CREATE TABLE CT_AGENDA
(
IDAGENDA INT IDENTITY NOT NULL,
IDTECNICO INT NOT NULL,
ESTADO CHAR(1) NOT NULL
CONSTRAINT  PK_AGENDA PRIMARY KEY (IDAGENDA),
CONSTRAINT CHK_ESTADO_AGENDA CHECK (ESTADO = 'A' OR ESTADO = 'M' OR ESTADO = 'B')
--OK VER FOREING ABAJO
)

CREATE TABLE CT_VISITA
(
IDVISITA INT IDENTITY NOT NULL,
IDAGENDA INT NOT NULL,
IDFACTURA INT,
IDPRESUPPUESTO INT,
IDCLIENTE INT NOT NULL,
IDDOMICILIO INT NOT NULL,
INICIOPROGRAMADO DATETIME NOT NULL,
FINPROGRAMADO DATETIME NOT NULL,
INICIOREAL DATETIME,
FINREAL DATETIME,
ESTADO CHAR(1) NOT NULL
CONSTRAINT PK_VISITA  PRIMARY KEY(IDVISITA),
CONSTRAINT CHK_ESTADO_VISITA CHECK (ESTADO = 'A' OR ESTADO = 'M' OR ESTADO = 'B')
-- OK VER ABAJO FOREING
)




CREATE TABLE CT_PRESUPUESTO
(
IDPRESUPUESTO INT IDENTITY NOT NULL,
FECHAEMISIONPRESUPUESTO DATE NOT NULL,
IDCLIENTE INT NOT NULL,
IDTECNICO INT NOT NULL,
TIEMPOMANOOBRA INT NOT NULL,
MONTOMANOOBRA INT NOT NULL
CONSTRAINT PK_PRESUPUESTO PRIMARY KEY (IDPRESUPUESTO),
CONSTRAINT CHK_TIEMPOMANOOBRA_PRESUPUESTO CHECK (TIEMPOMANOOBRA>0),
CONSTRAINT CHK_MONTOMANOOBRA_PRESUPUESTO CHECK (MONTOMANOOBRA>0)
--OK VER FOREING ABAJO
)







CREATE TABLE CT_ITEMPRESUPUESTO
(

IDITEMPRESUPUESTO INT IDENTITY NOT NULL,
IDPRESUPUESTO INT NOT NULL,
CODPRODUCTO CHAR(6) NOT NULL,
CANTPRODUTO INT NOT NULL,
MONTOITEM INT NOT NULL
CONSTRAINT PK_ITEMPRESUPUESTO  PRIMARY KEY (IDITEMPRESUPUESTO),
CONSTRAINT CHK_CANT_ITEMPRESUPUESTO CHECK (CANTPRODUTO>0),
CONSTRAINT CHK_MONTOITEM_ITEMPRESUPUESTO CHECK (MONTOITEM>0)
--OK VER FOREING ABAJO

)





CREATE TABLE CT_FACTURA
(
IDFACTURA INT IDENTITY NOT NULL,
FECHAEMISIONFACTURA DATE NOT NULL,
IDCLIENTE INT NOT NULL,
TIEMPOMANOOBRA INT NOT NULL,
MONTOMANOOBRA INT NOT NULL
CONSTRAINT PK_FACTURA PRIMARY KEY (IDFACTURA),
CONSTRAINT CHK_TIEMPOMANOOBRA_FACTURA CHECK (TIEMPOMANOOBRA>0),
CONSTRAINT CHK_MONTOMANOOBRA_FACTURA CHECK (MONTOMANOOBRA>0)
--OK VER FOREING ABAJO
)




CREATE TABLE CT_ITEMFACTURA
(
IDITEMFACTURA INT IDENTITY NOT NULL,
IDFACTURA INT NOT NULL,
CODPRODUCTO CHAR(6) NOT NULL,
CANTPRODUTO INT NOT NULL,
MONTOITEM INT NOT NULL
CONSTRAINT  PK_ITEMFACTURA PRIMARY KEY(IDITEMFACTURA),
CONSTRAINT CHK_CANT_ITEMFACTURA CHECK (CANTPRODUTO>0),
CONSTRAINT CHK_MONTOITEM_ITEMFACTURA CHECK (MONTOITEM>0)
--OK VER FOREING ABAJO
)





CREATE TABLE REP_ENCUESTA
(
IDENCUESTA INT IDENTITY NOT NULL,
IDVISITA INT NOT NULL,
ESTADO CHAR(1) NOT NULL
CONSTRAINT  PK_ENCUESTA PRIMARY KEY(IDENCUESTA),
CONSTRAINT CHK_ESTADO_ENCUESTA CHECK (ESTADO = 'A' OR ESTADO = 'M' OR ESTADO = 'B')
-- OK VER FOREING ABAJO

)




CREATE TABLE REP_PREGUNTAENCUESTA
(
IDPREGUNTAENCUESTA INT IDENTITY NOT NULL,
IDENCUESTA INT  NOT NULL,
IDPREGUNTA INT NOT NULL,
PUNTAJE INT NOT NULL
CONSTRAINT  PK_PREGUNTAENCUESTA PRIMARY KEY (IDPREGUNTAENCUESTA),
CONSTRAINT CHK_PUNTAJE_PREGUNTAENCUESTA CHECK (PUNTAJE > 0 AND PUNTAJE<=5)
-- OK VER FOREING ABAJO
)



CREATE TABLE REP_PREGUNTA
(
IDPREGUNTA INT IDENTITY NOT NULL,
DESCPREGUNTA VARCHAR(500) NOT NULL,
ESTADO CHAR(1) NOT NULL
CONSTRAINT  PK_PREGUNTA PRIMARY KEY(IDPREGUNTA),
CONSTRAINT CHK_ESTADO_PREGUNTA CHECK (ESTADO = 'A' OR ESTADO = 'M' OR ESTADO = 'B')
--OK NO TIENE FOREING
)


ALTER TABLE TG_DOMICILIO
ADD CONSTRAINT FK_DOMICILIO_PROVINCIA FOREIGN KEY (CODPROVINCIA) REFERENCES TG_PROVINCIA(CODPROVINCIA),
CONSTRAINT FK_DOMICILIO_CIUDAD FOREIGN KEY (CODCIUDAD) REFERENCES TG_CIUDAD(CODCIUDAD),
CONSTRAINT FK_DOMICILIO_CODIGOPOSTAL FOREIGN KEY (CODIGOPOSTAL) REFERENCES TG_CODIGOPOSTAL(CODIGOPOSTAL)

ALTER TABLE TG_CIUDAD
ADD CONSTRAINT FK_CIUDAD_PROVINCIA FOREIGN KEY (CODPROVINCIA) REFERENCES TG_PROVINCIA(CODPROVINCIA)



ALTER TABLE TG_CODIGOPOSTAL
ADD CONSTRAINT FK_CODIGOPOSTAL_PROVINCIA FOREIGN KEY (CODPROVINCIA) REFERENCES TG_PROVINCIA(CODPROVINCIA),
CONSTRAINT FK_CODIGOPOSTAL_CIUDAD FOREIGN KEY (CODCIUDAD) REFERENCES TG_CIUDAD(CODCIUDAD)

ALTER TABLE TG_USUARIO
ADD CONSTRAINT FK_USUARIO_ENTE FOREIGN KEY (IDUSUARIO) REFERENCES TG_ENTE(IDENTE)

ALTER TABLE TG_ENTE
ADD CONSTRAINT FK_ENTE_TIPODOC FOREIGN KEY (CODTIPODOCUMENTO) REFERENCES TG_TIPODOCUMENTO(CODTIPODOCUMENTO)

ALTER TABLE CT_CLIENTE
ADD CONSTRAINT FK_CLIENTE_ENTE FOREIGN KEY (IDCLIENTE) REFERENCES TG_ENTE(IDENTE),
 CONSTRAINT FK_CLIENTE_DOMICILIO FOREIGN KEY (IDDOMICILIO) REFERENCES TG_DOMICILIO(IDDOMICILIO)

ALTER TABLE CT_EMPLEADO
ADD CONSTRAINT FK_EMPLEADO_ENTE FOREIGN KEY (IDEMPLEADO) REFERENCES TG_ENTE(IDENTE),
CONSTRAINT FK_EMPLEADO_ROLLEMPLEADO FOREIGN KEY (CODROLLEMPPLEADO) REFERENCES TG_ROLLEMPPLEADO(CODROLLEMPPLEADO)

ALTER TABLE ST_RETIROPRODUCTO
ADD CONSTRAINT FK_RETIROPRODUCTO_DPRODUCTO FOREIGN KEY (IDPRODUCTO) REFERENCES ST_PRODUCTO(IDPRODUCTO),
CONSTRAINT FK_RETIROPRODUCTO_EMPLEADO FOREIGN KEY (IDTECNICORETIRANTE) REFERENCES CT_EMPLEADO(IDEMPLEADO)


ALTER TABLE ST_DEVOLUCIONPRODUCTO
ADD CONSTRAINT FK_DEVOLUCIONPRODUCTO_PRODUCTO FOREIGN KEY (IDPRODUCTO) REFERENCES ST_PRODUCTO(IDPRODUCTO),
CONSTRAINT FK_DEVOLUCIONPRODUCTO_TEC FOREIGN KEY (IDTECNICODEVOLUCION) REFERENCES CT_EMPLEADO(IDEMPLEADO),
CONSTRAINT FK_DEVOLUCIONPRODUCTO_ENCSTOCK FOREIGN KEY (IDENCRAGADOSTOCKDEVOLUCION) REFERENCES CT_EMPLEADO(IDEMPLEADO)


ALTER TABLE CT_AGENDA
ADD CONSTRAINT FK_AGENDA_TEC FOREIGN KEY (IDTECNICO) REFERENCES CT_EMPLEADO(IDEMPLEADO)



ALTER TABLE CT_VISITA
ADD CONSTRAINT FK_VISITA_AGENDA   FOREIGN KEY (IDAGENDA) REFERENCES CT_AGENDA(IDAGENDA),
CONSTRAINT FK_VISITA_FACTURA   FOREIGN KEY (IDFACTURA) REFERENCES CT_FACTURA(IDFACTURA),
CONSTRAINT FK_VISITA_RESUPUESTO   FOREIGN KEY (IDPRESUPPUESTO) REFERENCES CT_PRESUPUESTO(IDPRESUPUESTO),
 CONSTRAINT FK_VISITA_CLIENTE   FOREIGN KEY (IDCLIENTE) REFERENCES CT_CLIENTE(IDCLIENTE),
CONSTRAINT FK_VISITA_DOMICILIO  FOREIGN KEY (IDDOMICILIO) REFERENCES TG_DOMICILIO(IDDOMICILIO)


ALTER TABLE CT_PRESUPUESTO
ADD CONSTRAINT FK_PRESUPUESTO_TECNICO  FOREIGN KEY (IDTECNICO) REFERENCES CT_EMPLEADO(IDEMPLEADO),
CONSTRAINT FK_PRESUPUESTO_CLIENTE  FOREIGN KEY (IDCLIENTE) REFERENCES CT_CLIENTE(IDCLIENTE)

ALTER TABLE CT_FACTURA
ADD CONSTRAINT FK_FACTURA_CLIENTE  FOREIGN KEY (IDCLIENTE) REFERENCES CT_CLIENTE(IDCLIENTE)

ALTER TABLE CT_ITEMPRESUPUESTO
ADD CONSTRAINT FK_ITEMPRESUPUESTO_PRESUPUESTO  FOREIGN KEY (IDPRESUPUESTO) REFERENCES CT_PRESUPUESTO(IDPRESUPUESTO),
CONSTRAINT FK_ITEMPRESUPUESTO_PRODUCTO FOREIGN KEY (CODPRODUCTO) REFERENCES ST_PRODUCTO(CODPRODUCTO)


ALTER TABLE CT_ITEMFACTURA
ADD CONSTRAINT FK_ITEMFACTURA_FACTURA  FOREIGN KEY (IDFACTURA) REFERENCES CT_FACTURA(IDFACTURA),
CONSTRAINT FK_ITEMFACTURA_PRODUCTO FOREIGN KEY (CODPRODUCTO) REFERENCES ST_PRODUCTO(CODPRODUCTO)


ALTER TABLE REP_ENCUESTA
ADD CONSTRAINT FK_ENCUESTA_VISITA  FOREIGN KEY (IDVISITA) REFERENCES CT_VISITA(IDVISITA)


ALTER TABLE REP_PREGUNTAENCUESTA
ADD CONSTRAINT FK_REGUNTAENCUESTA_ENCUESTA FOREIGN KEY (IDENCUESTA) REFERENCES REP_ENCUESTA(IDENCUESTA),
CONSTRAINT FK_REGUNTAENCUESTA_PREGUNTA FOREIGN KEY (IDPREGUNTA) REFERENCES  REP_PREGUNTA(IDPREGUNTA)
